title: noteify
description: used by me, to manage all the lecture/study notes.
theme: just-the-docs


url: https://0xfrq.github.io/
baseurl: noteify/

aux_links:
  Repository: https://github.com/0xfrq/noteify
